account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('signup/',sign_up,name="sign_up"),
    path('signin/',sign_in,name="sign_in"),
    path('logout/',logoutuser,name="logout"),
    path('cart/',cart,name="cart"),
    path('addcart/',addcart,name="addcart"),
    path('deletecart/',deletecart,name="deletecart"),
]

configs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('',include('product.urls',namespace='product')),
    path('account/',include('account.urls',namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('',home,name='home'),
    path('shop/',shopall,name="shopall"),
    path('category/<str:c_name>/<int:c_id>/',category,name="category"),
    path('detail/<str:p_slug>/<int:p_id>',getdetail,name="product_detail")
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
# Create your models here.
class Cart(models.Model):
    usercart = models.OneToOneField(User,on_delete=models.CASCADE,related_name="usercart")

class CartProduct(models.Model):
    to_cart = models.ForeignKey(Cart,on_delete=models.CASCADE,related_name="to_cart")
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name="product")
    quantity = models.IntegerField(default=1)

    def bell(self):
        return (self.product.price * self.quantity) - ((self.product.price * self.quantity / 100) * self.product.discut)

    # def delete(self):
    #     self.product.delete()

product/models.py
from django.db import models
# Create your models here.
class Slider(models.Model):
    poster = models.ImageField("Tovar rasm",upload_to='sliderimgs/')
    name = models.CharField('Tovar nomi',max_length=300)
    name_plus = models.CharField('Tovar nomi qo\'shimcha',max_length=200,blank=True)
    about = models.TextField('Tovar haqida')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']

class Category(models.Model):
    poster = models.ImageField("Kategoriya rasm",upload_to='categoryimgs/')
    name = models.CharField("Kategoriya nomi",max_length=100)
    slug = models.SlugField("*",max_length=100,unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']

class Product(models.Model):
    poster = models.ImageField("Tovar rasm",upload_to='prductsimgs/')
    name = models.CharField("Tovar nomi",max_length=200)
    slug = models.SlugField("*",max_length=200,unique=True)
    price = models.IntegerField("Tovar narxi")
    about = models.TextField("Tovar haqida")
    star = models.IntegerField("Tovar yulduzchalari")
    discut = models.IntegerField("Tovar chegirmasi",blank=True,default=0)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="product_category")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .models import Cart,Product
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from account.models import Cart,CartProduct
# Create your views here.
def sign_up(request):
    username_error = False
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        if User.objects.filter(username=username):
            username_error = True
        else:
            user = User.objects.create_user(username=username, email=email, password=password, first_name=first_name)
            user.save()
            success = authenticate(username=username, password=password)
            login(request, success)
            createcart = Cart.objects.create(usercart=User.objects.get(id=request.user.id))
            return redirect("/")

    context = {
        "username_error":username_error,
        "exsit_username":request.POST.get('username')
    }
    return render(request,'sign_up.html',context)

def sign_in(request):
    in_error = False
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        success = authenticate(username=username, password=password)
        if success:
            login(request, success)
            return redirect("/")
        else:
            in_error = True
    context = {
        "in_error":in_error
    }
    return render(request,'sign_in.html',context)

def cart(request):
    return render(request,'cart.html')

def logoutuser(request):
    logout(request)
    return redirect("/")

@csrf_exempt
def addcart(request):
    if request.method == 'POST':
        try:
            cart = Cart.objects.get(usercart=request.user.id)
            CartProduct.objects.create(product_id=int(request.POST.get('pr_id')), to_cart_id=cart.id,
                                       quantity=int(request.POST.get('pr_quant')))
        except:
            pass
        return JsonResponse({"status":'save'})
    else:
        return JsonResponse({"status":'error'})

@csrf_exempt
def deletecart(request):
    if request.method == 'POST':
        try:
            cart = Cart.objects.get(usercart=request.user.id)
            trash = request.POST.get('tr_id')
            to_cart = CartProduct.objects.filter(to_cart_id=cart.id,product_id=trash)
            to_cart.delete()
            to_cart.save()
        except:
            pass
        return JsonResponse({"status": 200})

    else:
         return JsonResponse({"status":400})

product/views.py
from django.shortcuts import render
from .models import *
from django.contrib.auth.models import User
# Create your views here.
def home(request):
    return render(request,'index.html')

def shopall(request):
    return render(request,'shop.html')

def category(request,c_name,c_id):
    category = Category.objects.get(id=c_id,slug=c_name)
    category_product = Product.objects.filter(category=category)
    context = {
        "category_product":category_product,
        "category_name":category
    }
    return render(request,'category.html',context)

def getdetail(request,p_slug,p_id):
    product = Product.objects.get(slug=p_slug,id=p_id)
    context = {
        "detail_product":product
    }
    return render(request,'shop-single.html',context)

templates/cart.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="container pt-4 pb-4">
    <div class="card-header" style="border-top-left-radius:20px; border-top-right-radius:20px;">
        <div class="card-title">
            <h3>{{request.user.first_name}}</h3>
            <h5>{{request.user.email}}</h5>
            <h6>{{request.user.username}}</h6>
        </div>
    </div>
    <div class="pt-3 pb-2">
        <a href="" class="d-block text-center">
             <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
        </a>
        <a style="float:right; margin-right:20px; margin-top:-30px;">
            Total sum: <font class="text-success">{{sum_all}} So'm</font>
        </a>
    </div>
    <div>
        <table class="table table-hover " style="border-bottom-left-radius:20px;">
              <thead>
                <tr>
                  <th><small>id</small></th>
                  <th><small>nomi</small></th>
                  <th><small>rasmi</small></th>
                  <th><small>naxi</small></th>
                    <th><small>chegirma</small></th>
                    <th><small>soni</small></th>
                    <th><small>total</small></th>
                  <th><small>del</small></th>
                </tr>
              </thead>
              <tbody>
              {% for cart_items in cart_item %}
                <tr class="selected">
                  <th>{{cart_items.product.id}}</th>
                  <td>{{cart_items.product.name}}</td>
                  <td>
                      <img src="{{cart_items.product.poster.url}}" alt="" style="width:50px;">
                  </td>
                  <td>{{cart_items.product.price}}</td>
                    <td>-{{cart_items.product.discut}}%</td>
                    <td>{{cart_items.quantity}}</td>
                  <td>{{cart_items.bell}}</td>
                  <td>
                      <a   class="text-danger trash" id="{{cart_items.product.id}}">
                           <i class="fa fa-trash"></i>
                      </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
    </div>

</div>
{% endblock %}

 <script type="text/javascript">
     $('.trash').click(
        function (e){
        var trash_id = this.id
        var trashpaernt = this


          $.ajax({
              url:'{% url 'account:deletecart' %}',
              method:'POST',
              type:'json',
              data:{
              tr_id:trash_id
              },
              success: function(data){
              let tr_id = $(".trash").index(<trashp></trashp>aernt)

              $(".selected")[tr_id].style="display:none;"

              }
              })

        }
        )
 </script>

templates/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
   <!-- Start Banner Hero -->
    <div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
        <ol class="carousel-indicators">
            {% for len in lens %}
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="{{len}}" class="active"></li>
            {% endfor %}
        </ol>
        <div class="carousel-inner">
            {% for slider in sliders|slice:"0:1" %}
            <div class="carousel-item active">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="{{slider.poster.url}}" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left align-self-center">
                                <h1 class="h1 text-success">{{slider.name}}</h1>
                                <h3 class="h2">{{slider.name_plus}}</h3>
                                <p>
                                    {{slider.about}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% for slider in sliders|slice:"1:" %}
            <div class="carousel-item">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="{{slider.poster.url}}" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left align-self-center">
                                <h1 class="h1 text-success">{{slider.name}}</h1>
                                <h3 class="h2">{{slider.name_plus}}</h3>
                                <p>
                                   {{slider.about}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev text-decoration-none w-auto ps-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="prev">
            <i class="fas fa-chevron-left"></i>
        </a>
        <a class="carousel-control-next text-decoration-none w-auto pe-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="next">
            <i class="fas fa-chevron-right"></i>
        </a>
    </div>
    <!-- End Banner Hero -->


    <!-- Start Categories of The Month -->
    <section class="container py-5">
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">Categories of The Month</h1>
                <p>
                    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                    deserunt mollit anim id est laborum.
                </p>
            </div>
        </div>
        <div class="row">
            {% for category in categories|slice:"7" %}
            <div class="col-10 col-md-6 col-lg-4 col-xl-3 p-5 mt-3 m-auto ">
                <a href="{% url 'product:category' category.slug category.id  %}"><img src="{{category.poster.url}}" class="rounded-circle img-fluid border"></a>
                <h5 class="text-center mt-3 mb-3">{{category.name}}</h5>
                <p class="text-center"><a href="{% url 'product:category' category.slug category.id  %}" class="btn btn-success">Go Shop</a></p>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- End Categories of The Month -->
    <!-- Start Featured Product -->
    <section class="bg-light">
        <div class="container py-5">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Featured Product</h1>
                    <p>
                        Reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                        Excepteur sint occaecat cupidatat non proident.
                    </p>
                </div>
            </div>
            <div class="row">
                {% for product in products|slice:"0:6"%}
                <div class="col-12 col-md-4 mb-4">
                    <div class="card h-100"  style="border-radius:10px; box-shadow:0px 0px 20px -5px #c1c1c1;">
                        <a href="{% url 'product:product_detail' product.slug product.id %}">
                            <img src="{{product.poster.url}}" class="card-img-top" alt="{{product.name}}">
                        </a>
                        <div class="card-body">
                            <ul class="list-unstyled d-flex justify-content-between">
                                <li>
                                    {% for c in '0'|rjust:product.star|make_list  %}
                                    <i class="text-warning fa fa-star"></i>
                                    {% endfor %}
                                </li>
                                <li class="text-success text-right">{{product.price}} so'm</li>
                            </ul>
                             <ul class="list-unstyled d-flex justify-content-between">
                                <li>
                                    <span>Chegirmasi:</span>
                                </li>
                                <li class="text-success text-right">{{product.discut}}%</li>
                            </ul>
                            <a href="shop-single.html" class="h2 text-decoration-none text-dark">{{product.name|slice:"0:18"}}</a>
                            <p class="card-text">
                                {{product.about|slice:"0:100"}}
                            </p>
                            <a href="{% url 'product:product_detail' product.slug product.id %}" class="btn w-100 btn-block btn-primary">
                               <i class="fa fa-eye"></i> View
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- End Featured Product -->
{% endblock %}

templates/shop-single.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
 <!-- Open Content -->

    <section class="bg-light">
        <div class="container pb-5" >
            <div class="row">
                <div class="col-lg-5 mt-5">
                    <div class="card mb-3">
                        <img class="card-img img-fluid" src="{{detail_product.poster.url}}" alt="Card image cap" id="product-detail">
                    </div>
                </div>
                <!-- col end -->
                <div class="col-lg-7 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h2">{{detail_product.name}}</h1>
                            <p class="h3 text-success py-2">{{detail_product.price}} So'm</p>
                            <p class="h3 text-success py-2">Chegirmasi: {{detail_product.discut}}%</p>
                            <p class="py-2">
                                 {% for c in '0'|rjust:detail_product.star|make_list  %}
                                  <i class="fa fa-star text-warning"></i>
                                 {% endfor %}
                                <span class="list-inline-item text-dark">Rating {{detail_product.star}} | 36 Comments</span>
                            </p>
                            <h6>Description:</h6>
                            <p>{{detail_product.about}}</p>
                                <input type="hidden" name="product-title" value="Activewear">
                            {% if request.user.is_authenticated %}
                                {% if not request.user.is_staff %}
                                <div class="row">
                                    <div class="col-auto">
                                        <ul class="list-inline pb-3">
                                            <li class="list-inline-item text-right">
                                                Quantity
                                                <input type="hidden" name="product-quanity" id="product-quanity" value="1">
                                            </li>
                                            <li class="list-inline-item"><span class="btn btn-success" id="btn-minus">-</span></li>
                                            <li class="list-inline-item"><span class="badge bg-secondary" id="var-value">1</span></li>
                                            <li class="list-inline-item"><span class="btn btn-success" id="btn-plus">+</span></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="row pb-3">
                                    <div class="col-12 d-grid mb-4">
                                        <button id="addcart" type="button" class="btn btn-success btn-lg" name="submit" value="addtocard"><i class="fas fa-cart-plus"></i> Add To Cart</button>
                                    </div>
                                    <div class="col-12 mb-3">
                                        <p class="text-center">
                                            Enter comment
                                        </p>
                                        <textarea class="form-control w-100" placeholder="Entr your comment">

                                        </textarea>
                                    </div>
                                    <div class="col-12 text-end ">
                                        <a href="" class="btn btn-success ">
                                            Send
                                        </a>
                                    </div>
                                </div>
                                {% endif %}
                            {% else %}
                            <p class="text-center">
                                Siz ro'yhatdan o'tmagansiz xarid qilish uchun <a href="{% url 'account:sign_up' %}">Ro'yhatdan o'ting</a>
                            </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Close Content -->
    <div class="modal_cart alert alert-info">
        <div class="text-end">
            <a href="" class="close_cart" style="cursor: pointer; float: right;">
                <i class="fa fa-times"></i>
            </a>
        </div>
        <div class="alert-title text-center">
            <h4>Svatchaga qo'shildi </h4>
            <p>Nomi: {{detail_product.name}} </p>
            <p>Savatchaga <a href="{% url 'account:cart' %}">o'tish</a></p>
            <p></p>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<style>
    .modal_cart{position:absolute; width:20%; margin-left:40%; top:-200px; z-index:1; border-radius:10px; height:150px;}
</style>
<script>
 $(document).ready(
  $("#addcart").click(function (){
  $.ajax({
  url:'{% url 'account:addcart' %}',
  type:'POST',
  data:{
  pr_id:{{ detail_product.id }},
  pr_quant:$("#var-value").text(),
  },
  success:function (){
    document.querySelector('.modal_cart').style = "top:40%; transition:all 0.4s;"
    let text = Number(document.querySelector('.all_products').text())
    document.querySelector('.all_products').innerHTML = text++
  }
  })

  })
  )
   $(".close_cart").click(
   document.querySelector('.modal_cart').style = "top:-200px; transition:all 0.4s;"
   )
    </script>
{% endblock %}

templates/shop.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <!-- Start Content -->
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    {% for product in products %}
                    <div class="col-md-4">
                        <div class="card mb-4 product-wap rounded-0">
                            <div class="card rounded-0">
                                <img class="card-img rounded-0 img-fluid" src="{{product.poster.url}}">
                                <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                    <ul class="list-unstyled">

                                        <li><a class="btn btn-success text-white mt-2" href="{% url 'product:product_detail' product.slug product.id %}"><i class="far fa-eye"></i></a></li>
                                        {% if not request.user.is_staff %}
                                        <li><a class="btn btn-success text-white mt-2" href="{% url 'product:product_detail' product.slug product.id %}""><i class="fas fa-cart-plus"></i></a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                            <div class="card-body">
                            <ul class="list-unstyled d-flex justify-content-between">
                                <li>
                                    {% for c in '0'|rjust:product.star|make_list  %}
                                    <i class="text-warning fa fa-star"></i>
                                    {% endfor %}
                                </li>
                                <li class="text-success text-right">{{product.price}} so'm</li>
                            </ul>
                             <ul class="list-unstyled d-flex justify-content-between">
                                <li>
                                    <span>Chegirmasi:</span>
                                </li>
                                <li class="text-success text-right">{{product.discut}}%</li>
                            </ul>
                            <a href="shop-single.html" class="h2 text-decoration-none text-dark">{{product.name|slice:"0:18"}}</a>
                            <p class="card-text">
                                {{product.about|slice:"0:100"}}
                            </p>

                        </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div div="row">
                    <ul class="pagination pagination-lg justify-content-end">
                        <li class="page-item disabled">
                            <a class="page-link active rounded-0 mr-3 shadow-sm border-top-0 border-left-0" href="#" tabindex="-1">1</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link rounded-0 mr-3 shadow-sm border-top-0 border-left-0 text-dark" href="#">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link rounded-0 shadow-sm border-top-0 border-left-0 text-dark" href="#">3</a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <!-- End Content -->

    <!-- Start Brands -->
    <section class="bg-light py-5">
        <div class="container my-4">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Our Brands</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        Lorem ipsum dolor sit amet.
                    </p>
                </div>
                <div class="col-lg-9 m-auto tempaltemo-carousel">
                    <div class="row d-flex flex-row">
                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#multi-item-example" role="button" data-bs-slide="prev">
                                <i class="text-light fas fa-chevron-left"></i>
                            </a>
                        </div>
                        <!--End Controls-->

                        <!--Carousel Wrapper-->
                        <div class="col">
                            <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="multi-item-example" data-bs-ride="carousel">
                                <!--Slides-->
                                <div class="carousel-inner product-links-wap" role="listbox">

                                    <!--First slide-->
                                    <div class="carousel-item active">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_01.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_02.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_03.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_04.png" alt="Brand Logo"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End First slide-->

                                    <!--Second slide-->
                                    <div class="carousel-item">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_01.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_02.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_03.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_04.png" alt="Brand Logo"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End Second slide-->

                                    <!--Third slide-->
                                    <div class="carousel-item">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_01.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_02.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_03.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="/static/assets/img/brand_04.png" alt="Brand Logo"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End Third slide-->

                                </div>
                                <!--End Slides-->
                            </div>
                        </div>
                        <!--End Carousel Wrapper-->

                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#multi-item-example" role="button" data-bs-slide="next">
                                <i class="text-light fas fa-chevron-right"></i>
                            </a>
                        </div>
                        <!--End Controls-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Brands-->

{% endblock %}